"""Mappings to recognized security frameworks.

- IEC 62443 security zones & conduits (the ICS segmentation standard).
- MITRE ATT&CK Navigator layer export (a JSON heatmap of technique exposure that
  loads in https://mitre-attack.github.io/attack-navigator/).
"""
from __future__ import annotations

import json
from pathlib import Path

# Purdue level -> IEC 62443 security zone. 62443 does not prescribe exact names per
# Purdue level, but this is a conventional zoning of the reference model.
IEC_62443_ZONE = {
    "L0_PROCESS": "Process / Safety Zone",
    "L1_CONTROL": "Basic Control Zone (Cell/Area)",
    "L2_SUPERVISORY": "Supervisory Control Zone",
    "L3_OPERATIONS": "Operations / Site Manufacturing Zone",
    "L3_5_DMZ": "Industrial DMZ",
    "L4_ENTERPRISE": "Enterprise Zone",
    "L5_INTERNET": "External / Untrusted Zone",
}
_ZONE_ORDER = list(IEC_62443_ZONE)  # process -> external


def zone_of(asset) -> str:
    """The IEC 62443 zone an asset belongs to."""
    return IEC_62443_ZONE.get(asset.level.name, "Unspecified Zone")


def iec62443_zones(architecture) -> list[tuple[str, list[str]]]:
    """Assets grouped by IEC 62443 zone, ordered process -> external."""
    out: list[tuple[str, list[str]]] = []
    for level in _ZONE_ORDER:
        names = [a.name for a in architecture.assets.values() if a.level.name == level]
        if names:
            out.append((IEC_62443_ZONE[level], names))
    return out


def navigator_layer(architecture, mapped) -> dict:
    """Build an ATT&CK Navigator layer (domain ics-attack) from technique exposure.

    Each exposed technique is scored by the number of assets that expose it, with the
    asset names in the comment so the heatmap is self-explanatory in Navigator.
    """
    by_tech: dict[str, list[str]] = {}
    for name, data in mapped.items():
        for t in data.get("techniques", []):
            by_tech.setdefault(t["id"], []).append(name)

    max_score = max((len(v) for v in by_tech.values()), default=1)
    techniques = [
        {
            "techniqueID": tid,
            "score": len(assets),
            "enabled": True,
            "comment": ", ".join(sorted(assets)),
        }
        for tid, assets in sorted(by_tech.items())
    ]
    return {
        "name": f"{architecture.meta.get('name', 'ICS')} — technique exposure",
        "versions": {"attack": "17", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "ics-attack",
        "description": "Technique exposure generated by the Cyber-Physical Attack Surface Modeler.",
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffe8e8", "#fd8d3c", "#a50f15"],
            "minValue": 0,
            "maxValue": max_score,
        },
        "legendItems": [],
        "metadata": [],
        "hideDisabled": False,
    }


def write_navigator_layer(architecture, mapped, dest: str) -> str:
    """Write the ATT&CK Navigator layer JSON to `dest`; returns the path."""
    Path(dest).parent.mkdir(parents=True, exist_ok=True)
    Path(dest).write_text(json.dumps(navigator_layer(architecture, mapped), indent=2),
                          encoding="utf-8")
    return dest
