"""Briefing + plot generation.

Renders the structured vulnerability briefing and the three figures from the
asset / mapping / scoring / trends outputs. Matplotlib uses the Agg backend so it
runs headless.
"""
from __future__ import annotations

from pathlib import Path

from .frameworks import iec62443_zones

_LEVEL_ORDER = [  # process -> internet, for inventory grouping
    "L0_PROCESS", "L1_CONTROL", "L2_SUPERVISORY", "L3_OPERATIONS",
    "L3_5_DMZ", "L4_ENTERPRISE", "L5_INTERNET",
]


# --------------------------------------------------------------------------- #
# Briefing
# --------------------------------------------------------------------------- #
def generate_briefing(architecture, mapped, scores, paths, chokepoints_,
                      campaign_matches, violations=None, dest: str = "results/briefing.md") -> str:
    """Render the vulnerability briefing to `dest`; also returns the markdown."""
    assets = architecture.assets
    name = architecture.meta.get("name", "ICS reference architecture")
    violations = violations or []
    ranked = sorted(scores.items(), key=lambda kv: (-kv[1]["severity"], -kv[1]["impact"]))
    top_choke = max(chokepoints_.items(), key=lambda kv: kv[1]) if chokepoints_ else None

    L = []
    L.append(f"# Vulnerability Briefing — {name}\n")
    L.append("_Generated by the Cyber-Physical Attack Surface Modeler._\n")
    L.append("**Adversary modeled:** capable external actor (nation-state class) "
             f"entering at {', '.join(architecture.entry_nodes)}.\n")

    # Executive summary -----------------------------------------------------
    L.append("## Executive summary\n")
    bands: dict = {}
    for _, s in scores.items():
        bands[s["band"]] = bands.get(s["band"], 0) + 1
    band_line = ", ".join(f"{bands[b]} {b}" for b in
                          ["Very High", "High", "Moderate", "Low", "Very Low"] if b in bands)
    L.append(f"- Risk distribution: {band_line}.")
    top = [f"**{n}** ({s['band']})" for n, s in ranked[:3]]
    L.append(f"- Highest-risk assets: {', '.join(top)}.")
    if top_choke:
        L.append(f"- Most exposed waypoint (chokepoint): **{top_choke[0]}** "
                 f"(betweenness {top_choke[1]:.2f}) — sits on the most external→critical paths.")
    if paths:
        p = paths[0]
        L.append(f"- Easiest external→critical path: {' → '.join(p['path'])} "
                 f"({p['length']} hops, cost {p['cost']}, target risk {p['target_band']}).")
    if violations:
        L.append(f"- **{len(violations)} IT/OT segmentation bypass(es)** detected — see below.")
    L.append("")

    # Asset inventory -------------------------------------------------------
    L.append("## Asset inventory by Purdue level\n")
    for level in _LEVEL_ORDER:
        group = [a for a in assets.values() if a.level.name == level]
        if not group:
            continue
        L.append(f"**{level}**")
        for a in group:
            product = f" — {a.vendor} {a.product} {a.version}".rstrip() if a.product else ""
            proto = f" [{', '.join(a.protocols)}]" if a.protocols else ""
            L.append(f"- {a.name} ({a.component_type}){product}{proto}")
        L.append("")

    # Technique exposure ----------------------------------------------------
    L.append("## Technique exposure (asset × ATT&CK for ICS)\n")
    L.append("See `figures/heatmap.png` for the full matrix.\n")
    for n, _ in ranked:
        techs = mapped.get(n, {}).get("techniques", [])
        if not techs:
            continue
        labels = ", ".join(f"{t['id']}" + (f" ({t['name']})" if t['name'] else "") for t in techs)
        L.append(f"- **{n}**: {labels}")
    L.append("")

    # Segmentation findings -------------------------------------------------
    L.append("## Segmentation findings\n")
    if not violations:
        L.append("No direct IT→OT boundary bypasses — enterprise/internet assets reach "
                 "the OT zones only through the DMZ.\n")
    else:
        L.append("Connections that cross the IT/OT boundary **directly, skipping the "
                 "DMZ** — the segmentation control that should mediate them:")
        for v in violations:
            L.append(f"- **{v['from']}** ({v['from_zone']}) → **{v['to']}** ({v['to_zone']}) "
                     f"— flat path from IT into OT; highest-priority segmentation fix.")
        L.append("")

    # IEC 62443 zones & conduits -------------------------------------------
    L.append("## IEC 62443 zones & conduits\n")
    L.append("The architecture expressed in IEC 62443 terms — security **zones** (grouped "
             "assets) and the **conduits** that connect them.\n")
    for zone, names in iec62443_zones(architecture):
        L.append(f"- **{zone}**: {', '.join(names)}")
    if violations:
        bypass = "; ".join(f"{v['from']} → {v['to']}" for v in violations)
        L.append(f"\nConduit concern: IT→OT traffic should traverse the Industrial DMZ; "
                 f"the following conduit(s) bypass it — **{bypass}**.")
    else:
        L.append("\nAll IT→OT conduits are mediated by the Industrial DMZ.")
    L.append("\n_Reference: IEC 62443-3-3 — System security requirements and security levels._\n")

    # Attack-path findings --------------------------------------------------
    L.append("## Attack-path findings (easiest external→critical first)\n")
    L.append("_Paths respect the segmentation policy — edges the firewall denies are "
             "excluded. Cost = summed hop difficulty (unauthenticated hops are cheaper)._\n")
    if not paths:
        L.append("_No policy-permitted external→critical paths found._\n")
    for i, p in enumerate(paths, 1):
        L.append(f"{i}. [{p['length']} hops, cost {p['cost']}] {' → '.join(p['path'])} "
                 f"— target **{p['target']}** ({p['target_band']})")
    L.append("")

    # CVE summary -----------------------------------------------------------
    L.append("## Known-CVE summary\n")
    any_cve = False
    for n, _ in ranked:
        cves = mapped.get(n, {}).get("cves", [])
        if not cves:
            continue
        any_cve = True
        L.append(f"**{n}**")
        for c in sorted(cves, key=lambda c: -(c.get("cvss") or 0))[:5]:
            kev = " — **KEV (actively exploited)**" if c.get("known_exploited") else ""
            L.append(f"- {c['id']} — CVSS {c.get('cvss')} ({c.get('severity')}){kev}")
        L.append("")
    if not any_cve:
        L.append("_No CVEs attached — run the pipeline with CVE enrichment "
                 "(fetch_cves) to populate this section._\n")

    # Threat-trend mapping --------------------------------------------------
    L.append("## Threat-trend mapping (real campaigns vs. this architecture)\n")
    L.append("_Confidence = fraction of each campaign's characteristic techniques this "
             "architecture exposes. A match indicates **shared techniques**, not that the "
             "architecture is vulnerable to that specific malware._\n")
    for c in campaign_matches:
        if not c["matches"]:
            continue
        L.append(f"- **{c['name']}** ({c.get('year')}, {c.get('sector')}) — "
                 f"**{c['confidence']} confidence** "
                 f"({int(c['coverage'] * 100)}% technique coverage: "
                 f"{', '.join(c['matched_techniques'])})")
        top_assets = ", ".join(f"{m['asset']} ({int(m['fraction'] * 100)}%)"
                               for m in c["matches"][:4])
        L.append(f"    - most-exposed assets: {top_assets}")
    L.append("")

    # Mitigations -----------------------------------------------------------
    L.append("## Prioritized mitigation recommendations\n")
    for rec in _mitigations(architecture, mapped, scores, paths, top_choke):
        L.append(f"- {rec}")
    L.append("")

    # Figures ---------------------------------------------------------------
    L.append("## Figures\n")
    L.append("- `figures/network.png` — asset graph (color = Purdue level, size = impact)")
    L.append("- `figures/heatmap.png` — technique exposure matrix")
    L.append("- `figures/risk_matrix.png` — likelihood × impact, one point per asset")
    L.append("- `attack_navigator_layer.json` — load at mitre-attack.github.io/attack-navigator "
             "for a technique-exposure heatmap\n")

    # Scope & limitations ---------------------------------------------------
    L.append("## Scope & limitations\n")
    L.append("Stating what this analysis does *not* cover is deliberate — it is a "
             "static, model-based assessment, not a live audit.\n")
    L.append("- **Model, not network.** Analyzes a hand-authored architecture model — no "
             "traffic capture, scanning, or real device configuration is involved.")
    L.append("- **Attack paths are reachability, not exploits.** A path assumes a "
             "policy-permitted edge to an exploitable (e.g. unauthenticated) service is "
             "traversable; it does not model exploit reliability, chaining difficulty, or "
             "detection/response.")
    L.append("- **Segmentation is zone/protocol-level.** Boundaries are matched on the "
             "destination's protocols, not full firewall-rule semantics (5-tuples, NAT, "
             "deep inspection).")
    L.append("- **Scores are a documented heuristic.** The 800-30 Table I-2 combination is "
             "from the standard; the factor weights are engineering judgment, validated "
             "robust to ±20% perturbation for the *priority ranking* but not for "
             "fine-grained ordering among same-band assets (see `data/risk_rubric.md`).")
    L.append("- **CVEs match by product, point-in-time.** Matched by CPE vendor/product "
             "across versions (not pinned to exact firmware); KEV membership and CVE lists "
             "drift, so the snapshot should be refreshed.")
    L.append("- **Trend matches mean shared techniques**, not vulnerability to the specific "
             "malware. Technique mapping is rule-based and not exhaustive of ATT&CK for ICS.\n")

    text = "\n".join(L)
    Path(dest).parent.mkdir(parents=True, exist_ok=True)
    Path(dest).write_text(text, encoding="utf-8")
    return text


def _mitigations(architecture, mapped, scores, paths, top_choke) -> list[str]:
    recs = []
    if top_choke:
        recs.append(f"Harden the chokepoint **{top_choke[0]}** (segmentation, least-privilege "
                    "access, monitoring) — it is the highest-leverage single control.")
    if paths:
        entry = paths[0]["path"][0]
        recs.append(f"Constrain the fastest entry path via **{entry}** "
                    "(enforce the IT/OT DMZ, require MFA / brokered access for remote vendors).")
    # unauthenticated control-layer assets on the process side
    weak = [a.name for a in architecture.assets.values()
            if not a.authenticated and a.level.value <= 20 and a.protocols]
    if weak:
        recs.append(f"Add authentication / protocol-aware filtering for unauthenticated "
                    f"control assets: {', '.join(weak)}.")
    # KEV-flagged CVEs
    kev_assets = [n for n, m in mapped.items()
                  if any(c.get("known_exploited") for c in m.get("cves", []))]
    if kev_assets:
        recs.append(f"Patch actively-exploited (CISA KEV) CVEs on: {', '.join(kev_assets)}.")
    if not recs:
        recs.append("No high-priority findings — re-run after attaching CVE data.")
    return recs


# --------------------------------------------------------------------------- #
# Figures
# --------------------------------------------------------------------------- #
def _setup():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    return plt


def plot_network(graph, scores=None, dest: str = "results/figures/network.png") -> str:
    """Network diagram: color by Purdue level, node size by impact score."""
    import networkx as nx

    plt = _setup()
    scores = scores or {}
    for n in graph.nodes:
        graph.nodes[n]["layer"] = graph.nodes[n]["asset"].level.value
    pos = nx.multipartite_layout(graph, subset_key="layer", align="horizontal")
    levels = [graph.nodes[n]["asset"].level.value for n in graph.nodes]
    sizes = [300 + 35 * scores.get(n, {}).get("impact", 50) for n in graph.nodes]

    fig, ax = plt.subplots(figsize=(11, 8))
    nx.draw_networkx_edges(graph, pos, ax=ax, alpha=0.35)
    nodes = nx.draw_networkx_nodes(graph, pos, node_size=sizes, node_color=levels,
                                   cmap=plt.cm.viridis, ax=ax)
    nx.draw_networkx_labels(graph, pos, font_size=7, ax=ax)
    ax.set_title("ICS asset graph — color = Purdue level, size = impact")
    ax.axis("off")
    fig.colorbar(nodes, ax=ax, label="Purdue level (0 process → 50 internet)")
    Path(dest).parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(dest, dpi=120)
    plt.close(fig)
    return dest


def plot_exposure_heatmap(mapped, dest: str = "results/figures/heatmap.png") -> str | None:
    """Asset × technique exposure heatmap. Returns None if there is nothing to plot."""
    import numpy as np

    plt = _setup()
    assets = list(mapped)
    tech_ids = sorted({t["id"] for m in mapped.values() for t in m["techniques"]})
    if not tech_ids:
        return None
    matrix = np.array([[1 if tid in {t["id"] for t in mapped[a]["techniques"]} else 0
                        for tid in tech_ids] for a in assets])

    fig, ax = plt.subplots(figsize=(max(8, len(tech_ids) * 0.7),
                                    max(5, len(assets) * 0.45)))
    ax.imshow(matrix, aspect="auto", cmap="Reds")
    ax.set_xticks(range(len(tech_ids)))
    ax.set_xticklabels(tech_ids, rotation=60, ha="right", fontsize=7)
    ax.set_yticks(range(len(assets)))
    ax.set_yticklabels(assets, fontsize=7)
    ax.set_title("Technique exposure (asset × ATT&CK for ICS)")
    Path(dest).parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(dest, dpi=120)
    plt.close(fig)
    return dest


def plot_risk_matrix(scores, dest: str = "results/figures/risk_matrix.png") -> str:
    """Likelihood × impact scatter, one point per asset, colored by risk severity."""
    plt = _setup()
    fig, ax = plt.subplots(figsize=(8, 7))
    xs = [s["likelihood"] for s in scores.values()]
    ys = [s["impact"] for s in scores.values()]
    cs = [s["severity"] for s in scores.values()]
    ax.scatter(xs, ys, c=cs, cmap="YlOrRd", vmin=0, vmax=4, s=90, edgecolors="k", linewidths=0.4)
    for n, s in scores.items():
        ax.annotate(n, (s["likelihood"], s["impact"]), fontsize=6,
                    xytext=(3, 3), textcoords="offset points")
    for b in (20, 40, 60, 80):  # band gridlines
        ax.axhline(b, color="grey", lw=0.4, alpha=0.5)
        ax.axvline(b, color="grey", lw=0.4, alpha=0.5)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.set_xlabel("Likelihood")
    ax.set_ylabel("Impact")
    ax.set_title("Risk matrix (likelihood × impact)")
    Path(dest).parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(dest, dpi=120)
    plt.close(fig)
    return dest
